# Generated by Django 2.1.2 on 2018-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20181102_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='n_posts',
            field=models.IntegerField(default=0),
        ),
    ]
