# Generated by Django 2.1.2 on 2018-12-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20181222_1303'),
        ('question', '0007_auto_20181225_1758'),
    ]

    operations = [
    ]
